name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Python Script
      run: python3 app.py
